# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: cip60-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-cip60}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./cip60.sql:/docker-entrypoint-initdb.d/cip60.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
 
volumes:
  postgres-data:
